=== JesperTerkelsen/artifact-resolver/modules/artifact-resolver/src/main/resources/maven-metadata-v2_0_0.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
	targetNamespace="http://maven.apache.org/maven-metadata/2.0.0"
	xmlns="http://maven.apache.org/maven-metadata/2.0.0">
    <!-- This xsd is a guess and needs refining and testing -->
    <xs:element name="metadata">
        <xs:complexType>
            <xs:all>
                <xs:element name="groupId" minOccurs="1" maxOccurs="1"/>
                <xs:element name="artifactId" minOccurs="1" maxOccurs="1" type="xs:string"/>
                <xs:element name="version" minOccurs="0" maxOccurs="1" type="xs:string"/>
                <xs:element name="versioning" minOccurs="0" maxOccurs="1" type="Versioning"/>
            </xs:all>
        </xs:complexType>        
    </xs:element>
    <xs:complexType name="Versioning">
        <xs:sequence>
            <xs:element name="latest" minOccurs="0" maxOccurs="1" type="xs:string"/>
            <xs:element name="snapshot" minOccurs="0" maxOccurs="1" type="Snapshot"/>            
            <xs:element name="versions" minOccurs="0" maxOccurs="1"
				type="Versions">
            </xs:element>
            <xs:element name="lastUpdated" minOccurs="0" maxOccurs="1" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Versions">
        <xs:sequence>
            <xs:element name="version" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Snapshot">
        <xs:sequence>
            <xs:element name="timestamp" minOccurs="0" maxOccurs="1" type="xs:string"/>
            <xs:element name="buildNumber" minOccurs="0" maxOccurs="1" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>    
</xs:schema>

=== JesperTerkelsen/artifact-resolver/modules/artifact-resolver/src/main/resources/test-metadata1.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata xmlns="http://maven.apache.org/maven-metadata/2.0.0" 
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
             xsi:schemaLocation="http://maven.apache.org/maven-metadata/2.0.0 maven-metadata-v2_0_0.xsd">
  <groupId>com.infopaq.env</groupId>
  <artifactId>environment</artifactId>
  <versioning>
    <latest>1.2.0-SNAPSHOT</latest>
    <versions>
      <version>1.2.0-SNAPSHOT</version>
    </versions>
    <lastUpdated>20110808120607</lastUpdated>
  </versioning>
</metadata>

=== JesperTerkelsen/artifact-resolver/modules/artifact-resolver/src/main/resources/test-metadata2.xml
<metadata xmlns="http://maven.apache.org/maven-metadata/2.0.0" 
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
             xsi:schemaLocation="http://maven.apache.org/maven-metadata/2.0.0 maven-metadata-v2_0_0.xsd">
    <groupId>com.infopaq.env</groupId>
    <artifactId>environment</artifactId>
    <version>1.2.0-SNAPSHOT</version>
    <versioning>
        <snapshot>
            <timestamp>20110808.120607</timestamp>
            <buildNumber>62</buildNumber>
        </snapshot>
        <lastUpdated>20110808120607</lastUpdated>
    </versioning>
</metadata>
